### ISSUE TITLE
workflow_completed and workflow_continue_as_new counters should be logged after a successful reporting to the server

### ISSUE THREAD

**Issue by Spikhalskiy** [temporalio/features#222]
## Expected Behavior
`workflow_completed` metric counter is expected to count newly completed executions, accepted by the server.
A worker should log these metrics only after reporting the completion of the workflow task to the server and getting a confirmation from the server that the completion was not rejected.

## Actual Behavior
`workflow_completed` counter counts completion of workflow method code instead. Including replays and the ones that are followed by an `UNHANDLED_COMMAND` response from the Server for example.

## Additional Context
The same problem is present for `workflow_continue_as_new` counter.

## Tasks
* [ ] Go - https://github.com/temporalio/sdk-go/issues/2111
* [ ] Java - https://github.com/temporalio/sdk-java/issues/1590
* [ ] Core - https://github.com/temporalio/sdk-core/issues/1084
