### ISSUE TITLE
[Feature Request] Add API to count workflows

### ISSUE THREAD

**Issue by bergundy** [temporalio/features#234]
Similar to the list API but would return the count instead of an iterator.

See https://github.com/temporalio/api/blob/44e4397262d480b9e6f17771be9ae1812d97384e/temporal/api/workflowservice/v1/service.proto#L291 and https://github.com/temporalio/api/blob/44e4397262d480b9e6f17771be9ae1812d97384e/temporal/api/workflowservice/v1/request_response.proto#L749 for reference.

Checklist:

- [x] Go
- [x] temporalio/sdk-java#1685
- [x] temporalio/sdk-typescript/issues/1069
- [x] temporalio/sdk-python#294
- [x] temporalio/sdk-dotnet#30
- [x] temporalio/sdk-php#291

**Comment by bergundy** [comment]
Go supports this already, although the API isn't ideal.
I suggest leaving it as is.

```
CountWorkflow(ctx context.Context, request *workflowservice.CountWorkflowExecutionsRequest) (*workflowservice.CountWorkflowExecutionsResponse, error)
```

**Comment by cretz** [comment]
Note for those implementing this, be prepared to support a response with many values (see https://github.com/temporalio/api/pull/303). So don't just return an integer.
