### ISSUE TITLE
Worker Versioning API - Public Preview

### ISSUE THREAD

**Issue by bergundy** [temporalio/features#294]
https://docs.temporal.io/workers#worker-versioning

SDK checklist:
- [x] Go
- [x] Java
- [x] TypeScript
- [x] temporalio/sdk-python#335
- [x] temporalio/sdk-dotnet#99
- [x] temporalio/sdk-php#322
- [x] temporalio/sdk-ruby#140
