### ISSUE TITLE
[Feature Request] API key client option

### ISSUE THREAD

**Issue by cretz** [temporalio/features#426]
### Describe the solution you'd like

Every place that creates a client (nay a connection) should have an option to accept an API key which becomes the `Authorization` header of `Bearer <api-key>`. This is commonly used in self-hosted setups and will become common for cloud.

Client places:

* [x] Go - https://github.com/temporalio/sdk-go/issues/1401
* [x] CLI (after Go) - https://github.com/temporalio/cli/issues/478
* [x] Java - https://github.com/temporalio/sdk-java/issues/1997
* [x] Core - https://github.com/temporalio/sdk-core/issues/695
* [x] TypeScript (after Core) - https://github.com/temporalio/sdk-typescript/issues/1367
* [x] Python (after Core) - https://github.com/temporalio/sdk-python/issues/482
* [x] .NET (after Core) - https://github.com/temporalio/sdk-dotnet/issues/191
* [x] PHP - https://github.com/temporalio/sdk-php/issues/410

Thought was given to whether this should be lang only or core, but it became clear that "rpc metadata" (aka gRPC metadata aka headers) should remain separate from this setting all the way until headers are actually applied because people copy this client config in other places and it shouldn't just be a shallow alias for setting RPC metadata at that level.

**Comment by tlalfano** [comment]
Do we need to add PHP to the list here? @cretz

**Comment by cretz** [comment]
@tlalfano - yes, I just added it
