### ISSUE TITLE
User metadata and workflow metadata query

### ISSUE THREAD

**Issue by cretz** [temporalio/features#486]
### Describe the solution you'd like
Users need to provide certain bits of user metadata that is visible in the UI/CLI. Specifically from a user POV we will start out with:

* Fixed "static summary" and "static details" on workflow start (includes signal with start and child workflow and scheduled workflows)
  * EDIT: Late requirement - make sure these two items are available when describing a workflow and when describing a schedule of a workflow (will open issues for languages that don't have it)
* Updateable-within-workflow "current details" string
* Workflow metadata query that includes "current details" above and, if available, information about registered signals/queries/updates
* "summary" on timer start (can serve as "timer ID")
* "summary" on activity

The text format of summary/description is TBD (probably some form of mini markdown). More metadata may be added in the future.

### Per-Project Tickets
* [x] API - https://github.com/temporalio/api/pull/371
* [x] Server - https://github.com/temporalio/temporal/pull/5857 and https://github.com/temporalio/temporal/issues/6412 and https://github.com/temporalio/temporal/issues/6413
* [x] Go - https://github.com/temporalio/sdk-go/issues/1565 and https://github.com/temporalio/sdk-go/issues/1673
* [x] Java - https://github.com/temporalio/sdk-java/issues/2216 and https://github.com/temporalio/sdk-java/issues/335 and https://github.com/temporalio/sdk-java/issues/2268
* [x] Core - https://github.com/temporalio/sdk-core/issues/830
* [x] TypeScript - https://github.com/temporalio/sdk-typescript/issues/1544 (after Core)
* [x] Python - https://github.com/temporalio/sdk-python/issues/670 (after Core)
* [x] .NET - https://github.com/temporalio/sdk-dotnet/issues/359 (after Core)
* [x] Ruby - https://github.com/temporalio/sdk-ruby/issues/217
* [x] PHP - https://github.com/temporalio/sdk-php/issues/517 (after Go)
* [ ] Temporal CLI - https://github.com/temporalio/cli/issues/690 (after Go)

**Comment by Quinn-With-Two-Ns** [comment]
@cretz Is this issue a duplicate of https://github.com/temporalio/features/issues/51?

**Comment by cretz** [comment]
Yes, I think it basically is (or rather this includes that).
