### ISSUE TITLE
[Feature Request] High level API for schedules

### ISSUE THREAD

**Issue by bergundy** [temporalio/features#73]
The [Schedules](https://docs.temporal.io/workflows#schedule) feature is currently only exposed via raw gRPC or `tctl`.

SDKs should provide a friendly (high level) interface for this.

- [x] TS reference proposal temporalio/proposals/pull/62
- [x] Go temporalio/sdk-go#871
- [x] Java temporalio/sdk-java/issues/1333
- [x] TS temporalio/sdk-typescript/issues/794
- [x] Python temporalio/sdk-python/issues/87
- [x] .NET https://github.com/temporalio/sdk-dotnet/issues/23
- [x] PHP temporalio/sdk-php/issues/228

**Comment by bergundy** [comment]
@lorensr's assigned to come up with a TS proposal, for each SDK we'll roughly follow the proposal and adapt to fit language idioms.

**Comment by lorensr** [comment]
Thanks, fixed in OP

https://docs.temporal.io/workflows#schedule
